In [2]:
import numpy as np

In [4]:
lst1 = [1,2,3,4]
arr = np.array(lst1)
print(arr)

[1 2 3 4]


In [8]:
arr2 = np.array([4,5,6,7])
print(arr2)

[4 5 6 7]


In [13]:
arr_01 = np.zeros((2,3), dtype='int32')

In [16]:
arr_02 = np.ones((2), dtype='int32')
print(arr_02)

[1 1]


In [18]:
arr_03 = np.full((4,4),7)
print(arr_03)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [22]:
arr_04 = np.eye(3)
print(arr_04)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr_04 = np.arange(1,11,2)
print(arr_04)

[1 3 5 7 9]


In [33]:
arr_05 = np.empty((2,2))
print(arr_05)

[[0.00000000e+000 1.02992915e-311]
 [1.02992915e-311 1.02992915e-311]]


In [35]:
arr_06 = np.linspace(0,5,50)
print(arr_06)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [60]:
arr_06 = np.random.randn(2,2)
print(arr_06)

[[ 0.08534717  0.39326355]
 [ 0.56022961 -1.858882  ]]


In [81]:
arr_07 = np.random.rand(2,2)
print(arr_07)

[[0.20951955 0.74353504]
 [0.4071965  0.06325505]]


In [85]:
arr_08 = np.random.randint(0,10, size=(2,2))
print(arr_08)

[[5 3]
 [6 7]]


In [87]:
arr_01.shape

(2, 3)

In [89]:
arr_01.size

6

In [91]:
arr_01.ndim

2

In [93]:
arr_01.dtype

dtype('int32')

In [97]:
arr_01.astype(np.float64)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7])

In [109]:
print(array1 + array2)
print(array1 - array2)
print(array1 // array2)
print(array1 * array2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[0 0 0 0]
[ 5 12 21 32]


In [113]:
array1 @ array2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [124]:
arr_02 # 1,2
arr_05 # 2, 2
arr_10 = np.array([[1,2]])
arr_05 @ arr_10

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [129]:
print(np.sin(arr_06))
print(np.sqrt(arr_06))
print(np.power(arr_06, 3))

[[ 0.08524359  0.38320488]
 [ 0.53138072 -0.95878953]]
[[0.29214238 0.62710729]
 [0.74848488        nan]]
[[ 6.21680669e-04  6.08206558e-02]
 [ 1.75832107e-01 -6.42325949e+00]]


C:\Users\yousef elbaroudy\AppData\Local\Temp\ipykernel_13072\3190649676.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr_06))


In [159]:
lst1
lst2 = [0,6,-1,8]
lst1,lst2

([1, 2, 3, 4], [0, 6, -1, 8])

In [160]:
arr_11 = np.array(lst1)
arr_12 = np.array(lst2)
arr_11,arr_12

(array([1, 2, 3, 4]), array([ 0,  6, -1,  8]))

In [166]:
arr_06[arr_06 > 0.5]

array([0.56022961])

In [167]:
arr_12 = np.random.randint(0,15, size=(10,2))
arr_12[:4,1]

array([12,  9, 13,  9])

In [174]:
arr_05.sum(axis=1)

array([1.02992915e-311, 2.05985831e-311])

In [186]:
print(arr_12[:2,:].sum(axis=1))
print(arr_12[:2,:].mean(axis=1))
print(arr_12[:2,:].cumsum(axis=0))

[25 23]
[12.5 11.5]
[[13 12]
 [27 21]]


In [193]:
arr_02.reshape(1,2)

array([[1, 1]])

In [197]:
np.arange(10).reshape(2,5).ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
import pandas as pd

In [207]:
lst1
s = pd.Series(lst1, index=['a','b','c','d'])
s
s2 = pd.Series([4,5,6,7],index=[10,11,12,13])
print(s2)

10    4
11    5
12    6
13    7
dtype: int64


In [213]:
dictionary = {'ID':[1,2,3,4,5,6], 'Name':['Yousef','Ahmed','Tarek','Yasser','Khaled','Mohammed']}
df = pd.DataFrame(dictionary)
print(df)

   ID      Name
0   1    Yousef
1   2     Ahmed
2   3     Tarek
3   4    Yasser
4   5    Khaled
5   6  Mohammed


In [219]:
pd.DataFrame([lst1,lst2], columns=[10,11,12,13])

10  11  12  13
0   1   2   3   4
1   0   6  -1   8

In [225]:
df2 = pd.read_csv('train.csv', index_col='ID')

In [230]:
df2.head(1)

crim    zn  indus  chas    nox     rm   age   dis  rad  tax  ptratio  \
ID                                                                            
1   0.00632  18.0   2.31     0  0.538  6.575  65.2  4.09    1  296     15.3   

    black  lstat  medv  
ID                      
1   396.9   4.98  24.0

In [232]:
df2.tail()

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
ID                                                                              
500  0.17783  0.0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   
502  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
503  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
504  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
506  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

      black  lstat  medv  
ID                        
500  395.77  15.10  17.5  
502  391.99   9.67  22.4  
503  396.90   9.08  20.6  
504  396.90   5.64  23.9  
506  396.90   7.88  11.9

In [236]:
df2['crim']

ID
1      0.00632
2      0.02731
4      0.03237
5      0.06905
7      0.08829
        ...   
500    0.17783
502    0.06263
503    0.04527
504    0.06076
506    0.04741
Name: crim, Length: 333, dtype: float64

In [238]:
df2.iloc[:3,:2]

crim    zn
ID               
1   0.00632  18.0
2   0.02731   0.0
4   0.03237   0.0

In [239]:
df2.describe()

crim          zn       indus        chas         nox          rm  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean     3.360341   10.689189   11.293483    0.060060    0.557144    6.265619   
std      7.352272   22.674762    6.998123    0.237956    0.114955    0.703952   
min      0.006320    0.000000    0.740000    0.000000    0.385000    3.561000   
25%      0.078960    0.000000    5.130000    0.000000    0.453000    5.884000   
50%      0.261690    0.000000    9.900000    0.000000    0.538000    6.202000   
75%      3.678220   12.500000   18.100000    0.000000    0.631000    6.595000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.725000   

              age         dis         rad         tax     ptratio       black  \
count  333.000000  333.000000  333.000000  333.000000  333.000000  333.000000   
mean    68.226426    3.709934    9.633634  409.279279   18.448048  359.466096   
std     28.133344    1.981123    8.742174  170.841988    2.151821   86.584567   
min      6.000000    1.129600    1.000000  188.000000   12.600000    3.500000   
25%     45.400000    2.122400    4.000000  279.000000   17.400000  376.730000   
50%     76.700000    3.092300    5.000000  330.000000   19.000000  392.050000   
75%     93.800000    5.116700   24.000000  666.000000   20.200000  396.240000   
max    100.000000   10.710300   24.000000  711.000000   21.200000  396.900000   

            lstat        medv  
count  333.000000  333.000000  
mean    12.515435   22.768769  
std      7.067781    9.173468  
min      1.730000    5.000000  
25%      7.180000   17.400000  
50%     10.970000   21.600000  
75%     16.420000   25.000000  
max     37.970000   50.000000