In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
data = load_iris()
data.data
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
data_x = data.data
data_y = data.target
data_x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
data_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
full_data = np.hstack((data_x,data_y[:,np.newaxis]))

In [6]:
df = pd.DataFrame(full_data)
df

0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]

In [7]:
df.drop(df[df[4] == 2].index, inplace = True)

In [8]:
df

0    1    2    3    4
0   5.1  3.5  1.4  0.2  0.0
1   4.9  3.0  1.4  0.2  0.0
2   4.7  3.2  1.3  0.2  0.0
3   4.6  3.1  1.5  0.2  0.0
4   5.0  3.6  1.4  0.2  0.0
..  ...  ...  ...  ...  ...
95  5.7  3.0  4.2  1.2  1.0
96  5.7  2.9  4.2  1.3  1.0
97  6.2  2.9  4.3  1.3  1.0
98  5.1  2.5  3.0  1.1  1.0
99  5.7  2.8  4.1  1.3  1.0

[100 rows x 5 columns]

In [9]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.3)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

In [12]:
model.fit(X_train,y_train)

KNeighborsClassifier()

In [17]:
prediction = model.predict(X_test)
print(prediction)

[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1.
 0. 1. 0. 1. 0. 1.]


In [14]:
model.score(X_test,y_test)

1.0

In [15]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion='entropy')

In [16]:
DT.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [18]:
prediction2 = DT.predict(X_test)
print(prediction2)

[0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1.
 0. 1. 0. 1. 0. 1.]


In [19]:
DT.score(X_test, y_test)

1.0